---

- name: "Creating kubeadm-join-master.sh script.."
  template:
    src: kubeadm-join-master.sh.j2
    dest: /root/kubeadm-join-master.sh
    owner: root
    group: root
    mode: 755

# Params from kubeadm init:
#   token
#   discovery_token_ca_cert_hash
#   certificate_key
#
- name: "Include variables from join-params.yaml"
  include_vars:
    file: working-files/join-params.yaml

- name: "Generating ConfigMap YAML file.."
  template:
    src: kubeadm-master-join-configmap.yaml.j2
    dest: /root/kubeadm-master-join-configmap.yaml
    owner: root
    group: root
    mode: 644

- name: "Running kubeadm join master with config file.."
  shell: /root/kubeadm-join-master.sh 2>&1 | /bin/tee -a /root/kubeadm-join-master.log
  args:
    executable: /bin/sh
    chdir: /root
    creates: /root/kubeadm-join-master.log

