---

- hosts: infra-host masters nodes
  roles:
  - ntp
  - pre-deploy
##  - update-packages # takes a while so commented out 
  - firewall
  - docker-install
  - kube-repo

- hosts: infra-host
  roles:
  - set-hostname
  - deploy-bind-docker
  - config-resolv-conf
  - kube-yum-versionlock
  - kubectl-cli-install

- hosts: masters nodes
  roles:
  - config-resolv-conf
  - kube-yum-versionlock
  - kube-kubeadm-install

- hosts: master1
  roles:
  - kube-kubeadm-init-master1
  - pause-minutes
  - kube-add-calico-cni
  - kube-add-storageclass

- hosts: master2 master3
  roles:
  - kube-kubeadm-join-master
  - pause-minutes

- hosts: nodes
  roles:
  - kube-kubeadm-join-node

